### PR TITLE
Initial 'dev' packagegroup, including openssh-sftp-server

### PR DESCRIPTION
**Pull request by tom--pollard**
[GDP-230] Create a packagegroup for dev tools

### CODE REVIEW

**Comment by chbae** [comment]
If you apply this PR, the sftp server is automatically started?

**Comment by tom--pollard** [comment]
Yes @chbae , I've tested this locally when enabled on the porter:

tom@pollard:~$ sftp root@10.24.3.17
root@10.24.3.17's password: 
Connected to 10.24.3.17.
sftp>

sshd_config can be modified the user to change default behaviour

**Comment by tom--pollard** [comment]
I'd plan to add packages such as stated in connman-client [GDP-191] to this packagegroup once initially merged

**Comment by chbae** [comment]
+1 This is fine to me.

**Comment by rkrauseics** [comment]
Could we please add udisks2 to this dev package group

**Pull request merged**
