### PR TITLE
genivi-dev-platform: Fix wifi recognition for rpi3

### PR DESCRIPTION
**Pull request by chbae**
[GDP-399] Enable wifi on RPI 3

Signed-off-by: Changhyeok Bae changhyeok.bae@gmail.com

### CODE REVIEW

**Comment by chbae** [comment]
I tested wifi feature on rpi3.

**Comment by tom--pollard** [comment]
@chbae Is it not safer to just bring in 'packagegroup-base-wifi' than the whole of the packagegroup-base?

**Comment by chbae** [comment]
@tom--pollard 
For enabling wifi, GDP needs firmware depended on packagegroup-base (packagegroup-machine-base). Not packagegroup-base-wifi. :)
Actually GDP should enable MACHINE_EXTRA_RRECOMMENDS += "linux-firmware-brcm43430" in  meta-raspberryp/conf/machine/raspberrypi3.conf

Thanks for your comment.

**Comment by tom--pollard** [comment]
@chbae 
I tried adding the firmware and exta distro features from here http://raspberrypi.stackexchange.com/questions/49970/setting-up-in-built-bluetooth-from-raspberrypi3-using-image-created-with-yocto-j as reported in jira, but it didn't seem to be the solution. Although I may well have been missing some configuration

**Comment by chbae** [comment]
With this pull request, device driver is added and wlan0 is grabbed. However, I didn't test wifi fully.

**Comment by chbae** [comment]
I successfully tested wifi connection.

**Comment by chbae** [comment]
I thought that it's fine to merge this PR and then we can close GDP-399
@RobertAJMarshall @tom--pollard 
Please give your opinion.

**Review by RobertAJMarshall — COMMENTED** [review]
Yes, I'm happy for it to be merged

**Pull request merged**
