### PR TITLE
Improve systemd service cfg

### PR DESCRIPTION
**Pull request by phongt**
@zeenix Please consider to merge this.

### CODE REVIEW

**Comment by chbae** [comment]
I recommend that you change title to belows
- genivi-swm: Remove executable bits systemd service cfg
- rvi-sota-client: Fix timeout definition of sota_client.service

**Comment by phongt** [comment]
@chbae  Thanks. I updated the commit title.

**Review by zeenix — COMMENTED** [review]
Change looks good but I'd want some fixes in commit log. To encourage new contributions, I'll fix these myself but wanted to mention for future reference:

* Shortlog should be around 50 chars (ideally less)
* Shortlog should summarise the change, not the effect and avoid vague terms like "Fix".
* No need to break lines for starting a new sentence but rather to avoid going over 74 characters or starting a new paragraph. 
* typo: sutable -> suitable

**Comment by zeenix** [comment]
@phongt I pushed changes to your log messages. Please check if I didn't mess up anything by accident or if you see some mistakes (I make them too). :)

BTW :+1: for dividing your changes into logical commits!

**Comment by phongt** [comment]
@zeenix Thank you, LGTM.

**Pull request merged**
