### PR TITLE
Enable DRM backend for qemux86-64 image

### PR DESCRIPTION
**Pull request by tom--pollard**
[GDP-166] QEMU GFX performance drop

Enabling DRM kernel modules and gallium support in mesa. This allows
weston to use the drm-backend, when -vga std/virtio is used on the
kvm host.

### CODE REVIEW

**Comment by tom--pollard** [comment]
I've pushed this to hopefully receive feedback via testing. The image should be launched in the same manner but with -vga std instead of -vga vmware. Testing internally has shown differing results dependant on the hosts qemu kvm version. Enabling the gallium drivers in mesa also shows improvement gains with the regular fbdev backend

**Comment by RobertAJMarshall** [comment]
Builds and runs ok for me here

**Comment by chbae** [comment]
it looks fine if test performance is ok.

**Comment by tom--pollard** [comment]
This still requires further testing by other users, drm with -std has cursor issues as documented in jira on my 14.04 qemu kvm package

**Comment by tom--pollard** [comment]
I plan to test this on more host systems this week

**Comment by tardyp** [comment]
I tested http://docs.projects.genivi.org/gdp_files/v11/rc1/qemux86-64/gdp-11-rc1-qemu.ext4.gz with 1404 qemu kvm, and it also has cursor issues with fbdev driver

**Comment by tom--pollard** [comment]
I think the best option for supporting DRM would be to make it user configurable at init time or via local.conf. However this would require a sure way of acquiring if the kvm host system was compatible with the required kvm/qemu kernel version etc

**Comment by zeenix** [comment]
So what's the status of this PR?

**Comment by zeenix** [comment]
So I built this PR successfully and was about to launch GDP in Qemu with it but I had to change "-vga vmware" to "-vga std". "-vga virtio" didn't work for me, the HMI didn't launch with that option. Shall I just merge this and update the Qemu commandline in the wiki?

**Comment by zeenix** [comment]
@tom--pollard ?

**Comment by tom--pollard** [comment]
I would vote against merging this as the output is dependant on the host qemu/kvm version.  It would have to be optional in init.sh. I know for instance (as documented in JIRA) that it will not work for 14.04 hosts

**Comment by tardyp** [comment]
if qemu is already unusable because of its performance, would it make sense to not wait until somebody finds a init.sh script, and drop support for 14.04 hosts?

m2c

**Comment by zeenix** [comment]
@tom--pollard by 14.04 you mean Ubuntu I assume (let's not make that implicit assumption in GDP :)).

@tardyp Not sure what you mean. Find a init.sh where? We shouldn't drop support for Ubuntu 14.04 IMO.

**Comment by zeenix** [comment]
@tardyp I know you must be busy so I wanted to remind you that I wait for your clarification. :)

@tom--pollard The commandline is already different for different hosts so I'm not sure anything will change there. Correct?

**Comment by tardyp** [comment]
@zeenix I was refering to @tom--pollard suggestion that there is a magic init.sh script to be written, which would detect buggy DRM implementation, and disable drm in those cases.

my point is that anyway if DRM is disabled, then the UI is not usable so we should keep the solution simple and only support recent qemu hosts.
m2c in the hope it helps

**Comment by zeenix** [comment]
@tardyp Thanks so much for explaining! Yes, I see what you mean now and I completely agree.

**Comment by gunnarx** [comment]
Converted to apply to genivi-dev-platform instead, after meta-genivi-dev subtree addition 
--> https://github.com/GENIVI/genivi-dev-platform/pull/96
Closing this one.

**Pull request closed without merging**
