### PR TITLE
Updates to support meta-ivi11.0 (MIRANDA) & Yocto 2.1

### PR DESCRIPTION
**Pull request by tom--pollard**
[GDP-281] - Upgrade GDP Master to baseline 11 (MIRANDA)

### CODE REVIEW

**Comment by tom--pollard** [comment]
Once meta-genivi-dev can support ivi11/yocto2.1 I will send a PR to genivi-dev-platform to bring in this ref + corresponding submodule updates.  If the PR for qt5.6 is merged beforehand I will rebase  & ammend this PR. This is only initial 'beta' support. Currently this requires avoiding building AudioManagerPlugins as a separate recipe/package as provided by meta-ivi.

**Comment by chbae** [comment]
@tom--pollard 
- I removed audiomanager commit in my repo.
  And then, could you remove this commit "Audiomanager: Revert SRC_URI_remove override & SRC_URI_append" in my forked rep?
- IVI11 beta is released and it uses higher version's weston and wayland-ivi-extension. So I'm upgrading in my repo.

**Comment by tom--pollard** [comment]
@chbae I've built this against ivi11 branch (not experimental) and has no issues with weston / ivi-extension.

And yes I can forcefully remove  both of the src_uri patches to audiomanager. I also see that you've managed to split the pulse paths for the new audioplugins recipe which is nice!

*my mistake, still using weston 1.9!

**Comment by tom--pollard** [comment]
I'm closing this PR, a new PR will be sent shortly

**Pull request closed without merging**
