### PR TITLE
Add features to support raspberrypi3

### PR DESCRIPTION
**Pull request by chbae**
- Change raspberrypi2 variable to rpi
- Add configuration for raspberrypi3 serial support

[GDP-128] GDP-ivi9 on RPi3

Signed-off-by: Changhyeok Bae changhyeok.bae@gmail.com

### CODE REVIEW

**Comment by chbae** [comment]
This PR should be merged before https://github.com/GENIVI/genivi-dev-platform/pull/13

**Comment by tom--pollard** [comment]
Hi @chbae , these changes seem sensible ( I like the switch to the soc_family 'rpi' appends instead of specific 2/3). I'm unable to test this image on a raspi3 as I do not own one, but I trust you have tested it. I wonder if any contributors with access to a raspi3 could try it?

**Comment by chbae** [comment]
@tom--pollard  We can request to @leon-anavi 

@leon-anavi  Could you please test this on your raspberrypi3?

**Comment by leon-anavi** [comment]
Hi @chbae I was going to report the issue about "an invalid target name was given of raspberrypi3" when I saw you message. Thank you for the fix. I will have a look at it.

**Comment by tom--pollard** [comment]
Just rebuilt on top of my raspi2 build env, so no complaints build wise from me.

**Comment by tom--pollard** [comment]
@leon-anavi Has reported a successful deployment in https://github.com/GENIVI/genivi-dev-platform/pull/13 , so +1 from me :)

**Pull request merged**
