### PR TITLE
rvi-default-config: Update /etc/sota.toml

### PR DESCRIPTION
**Pull request by leon-anavi**
Update the default RVI configurations for Aktualizr, the SOTA client
written in C++, by adding paths to keys and certicates in sota.toml.

[GDP-551] Integrate Aktualizr (SOTA Client C++)

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

### CODE REVIEW

**Review by zeenix — COMMENTED** [review]
shot log very vague but sure. Let's see the CI builds..

**Review by chbae — APPROVED** [review]

**Comment by zeenix** [comment]
The two failing builds are due to the usual agent problem. I'll merge this...

**Comment by gunnarx** [comment]
> The two failing builds are due to the usual agent problem. I'll merge this...

?   

Maybe you were just tired when you wrote it but for the record those builds are failing because they are failing or not supported, not the build agents' fault.   :)

**Comment by zeenix** [comment]
@gunnarx Don't have access anymore but I only saw that "no such file or directory" we've been seeing for a while. I forgot if it's agent's fault or not but at least it's unlikely to be caused by this PR.

**Pull request merged**
