### PR TITLE
Fix encoding error on RPI

### PR DESCRIPTION
**Pull request by nicolas4119**
[GDP-332] Encoding problems in qml-example on gdp master using a RPI2/3

Update qtquickcontrols recipe : remove renderType parameters in some qml files

### CODE REVIEW

**Comment by nicolas4119** [comment]
I wrote those patches, but i dont know if the bug is directly from Qt. 
It could be a problem with the nativeRendering on the Pi with Genivi. Plus i made the textField and label work, but there is probably more files to change if we want to use all qtquickcontrols features.

**Comment by tom--pollard** [comment]
The vc4 renderer has had problems before on Pi, which have slowly resolved over time. The patch looks sane enough to me, and keeping it to rpi only reduces the risk

**Comment by gunnarx** [comment]
Interesting but having to keep different qml code for different hardware targets feels really strange to me.

@nicolas4119 After this you may want to track https://github.com/GENIVI/hmi-layout-gdp which is likely to be the next GDP HMI shortly - there is some work left to integrate the application launching however - I think anyone who can contribute QML patches there would be much appreciated.

**Comment by gunnarx** [comment]
Oops sorry, did not mean to close.
On topic - is this patching qtquickcontrols?   I would agree with @chbae that this is probably something to discuss with Qt upstream then - they may have an explanation or better solution.

**Comment by tom--pollard** [comment]
Hi @nicolas4119 , would it be possible you to add a signed off line (see here https://www.genivi.org/contribute) to the commit message body, thanks :)

**Comment by zeenix** [comment]
I tested this here and seems while the encoding issue is resolved but it's very hard to tell cause the text is now extremely small.

**Comment by zeenix** [comment]
Ah, please ignore my last comment. The text was already pretty tiny on Minnowboard + faytech monitor so I thought it's the same issue of text encoding. I think it's a different issue.

**Comment by zeenix** [comment]
The patch fixes the encoding in the entry but text on the button is not quite right, at least on the 800x600 RPI touchscreen. However the patch is missing the signed-off-by and jira reference. Nicolas, can you please fix that?

**Comment by zeenix** [comment]
I merged it manually so I can sign it off.

**Pull request closed without merging**
