### PR TITLE
Support official 7 inch touch screen for RPI

### PR DESCRIPTION
**Pull request by chbae**
[GDP-206] Support official 7 inch touch screen for RPI

Signed-off-by: Changhyeok Bae changhyeok.bae@gmail.com

### CODE REVIEW

**Comment by tom--pollard** [comment]
Confirmed this builds ok, and the commits are as I expect from the upstream PR's from anholt. As mentioed once meta-raspberrypi move to 4.4.16 we will be able to revert the src_uri override.

**Comment by RobertAJMarshall** [comment]
Builds ok for me too

**Comment by chbae** [comment]
May I merge this commit tonight?

**Comment by RobertAJMarshall** [comment]
I'm happy for this merge to take place

**Comment by chbae** [comment]
Thanks. I'll merge this tomorrow :)

**Pull request merged**
