### PR TITLE
genivi-dev-platform: Add IoTivity package group from oic

### PR DESCRIPTION
**Pull request by rzr**
Bug: https://at.projects.genivi.org/jira/browse/GOCF-27
Change-Id: I4b07a5f7ab995df8db83f54cb14710e600f4d0da
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

Please merge 
https://github.com/GENIVI/genivi-dev-platform/pull/52 
before or at the sametime

For support ask me or check:

https://wiki.iotivity.org/automotive
https://wiki.iotivity.org/yocto
https://wiki.iotivity.org/examples

### CODE REVIEW

**Comment by rzr** [comment]
As 
https://github.com/GENIVI/genivi-dev-platform/pull/52
is just merged you can also consider adding iotivity to GDP, 
it will help to support ocf automotive demos

**Comment by gunnarx** [comment]
@rzr I'm glad to see more iotivity stuff coming in.   

Just a question - are those demos scheduled to be included in GDP Master soon?  Basically I think the services should be enabled in GDP Master kind of near the same time as there is a demonstration that is reasonably easy for users to run.  I did a little looking at the content of this package group and found a few services and iotivity-simple-client, but to be honest I don't know much about its usage.  What can we do with it?  @zeenix - I suppose you talk to rzr as often as you can? :-)

**Comment by rzr** [comment]
Well those examples are reference unit tests to validate ocf stack, 

To get started you can check this short article
https://blogs.s-osg.org/run-iotivity-artik-yocto/

While our demo apps were supposed to be ship in meta-genivi-ocf-demo but this proposal was rejected, 
so I changed the strategy to do it in longer term and  proceed step by steps, so having iotivity part of GDP seems legit as layer is already part if project ;)

Regards

**Comment by gunnarx** [comment]
Hashed it out on irc with rzr.  No services are enabled, just a few small libs and binaries built and deployed.  So this is no big deal.  @zeenix you decide how to handle release/master branch strategy but I'd take this.

**Comment by gunnarx** [comment]
FYI, build of the PR passed on 4 tested targets:
https://go.genivi.org/go/pipelines/GDP-Yocto-MINNOWBOARD-meta-genivi-dev-GITHUB-PR/43/build/1
(x 4).

**Comment by rzr** [comment]
ok cool, yea don't be confused service subpackage is just extra library nothing will be started at boot time

**Comment by rzr** [comment]
@zeenix hi, any ETA for this then I'll focus on how to upgrade to 1.2.0 after it is landed in GDP

cc: @iamsanjeev / @as2902b

**Comment by zeenix** [comment]
I'm currently on vacation so can't look at details etc but I'm very reluctant to merge anything before release 11 happens.

**Comment by rzr** [comment]
OK meanwhile I will document on how GDP users can work with it from this wiki page:
https://wiki.iotivity.org/automotive

**Comment by rzr** [comment]
Once integrated I will update meta-oic to 1.2.0 as I recently shared recipe to upstream

Meanwhile private repo can be used as explained on:

https://wiki.iotivity.org/automotive

**Comment by rzr** [comment]
@zeenix , since gdp-11 is released, It would be nice to test this patch before I upgrade meta-oic to 1.2.0 and pull also iotivity-node from meta-iot-web

cc: @gunnarx , @iamsanjeev / @as2902b

**Comment by zeenix** [comment]
@rzr It's not completely released yet. :)

**Comment by rzr** [comment]
Thanks, more to come at:
https://wiki.iotivity.org/automotive

**Pull request merged**
