### PR TITLE
rvi-sota-client: Drop sota_sysinfo.sh & it's deps

### PR DESCRIPTION
**Pull request by zeenix**
If I have understood correctly, we can drop this without loosing any essential functionality and it fixes a bug too:

https://at.projects.genivi.org/jira/browse/GDP-541

### CODE REVIEW

**Comment by gunnarx** [comment]
Obviously I'm in favor, mostly because of time availability.  I have not been able to fully confirm (or at least not understand) if this is a local Go-agent problem or something fundamental on all build agents, or if it's just intermittent and we are misreading the clues.  

But to buy us some time even if it is Go server related, I would support dropping what we don't need here...
Can we get the SOTA and/or Rust people to confirm it's OK?

**Comment by zeenix** [comment]
@gunnarx the discussion is in the JIra ticket: https://at.projects.genivi.org/jira/browse/GDP-541 . If I understood correctly, yes they seem fine with dropping this script.

**Comment by zeenix** [comment]
@gunnarx now getting another issue in go.cd for this PR:

18:01:31.736 | /var/lib/go-agent/pipelines/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/gdp/gdp-src-build/tmp/work/core2-64-poky-linux/navigation-service/1-r0/git/src/navigation/navigation-core/configuration-plugin/genivi_navigationcore_configuration.cxx:285:66: error: 'event_request_system' was not declared in this scope
18:01:31.736 |   event_request_system("glib","genivi_navigationcoreconfiguration");
18:01:31.736 |                                                                   ^

**Review by DunderRoffe — APPROVED** [review]
Looks OK. Assuming this is manually tested I am fine with merging this @zeenix

**Comment by zeenix** [comment]
@chbae can you check and merge?

**Comment by chbae** [comment]
@zeenix 
I'll check and will merge tonight.
Thanks.

**Comment by chbae** [comment]
@zeenix 
Please remove "${bindir}/sota_sysinfo.sh \" in FILES_${PN} of rvi-sota-client_git.bb

**Comment by zeenix** [comment]
@chbae thanks, I pushed an update.

**Comment by chbae** [comment]
@zeenix 
I just successfully built and I believe you and @DunderRoffe 's test result.
And I recommend that it's better to use your forked github repository instead of branch in this repo.

Thanks

**Comment by zeenix** [comment]
Thanks @chbae . You mean we should create forks for PRs rather than branches? We could certainly do that but could you please explain why that should be preferred?

**Comment by chbae** [comment]
@zeenix 
>You mean we should create forks for PRs rather than branches?

Right.

>We could certainly do that but could you please explain why that should be preferred?

GENIVI/meta-genivi-dev is official repository and only maintainers can create branch.
Sometimes developers can confuse those working branches. So I recommend that you create your own forked repo.

Thanks

**Comment by zeenix** [comment]
@chbae Makes sense, thanks. Could you do me a favour and send an email to the list mentioning this preference so that everyone knows? Also let's add this to: https://at.projects.genivi.org/wiki/display/PROJ/How+to+contribute+to+GENIVI

**Comment by chbae** [comment]
@zeenix 
I can do it but only maintainers (maybe you and I) can create branch in GENIVI official repository. :)

**Comment by zeenix** [comment]
Actually I thought more on this and I don't agree. :)

> I can do it but only maintainers (maybe you and I) can create branch in GENIVI official repository. :)

Yes but that's not a problem since people who can't create branches, then fork instead and add their branch in there.

About devs getting confused, there is a common practice among many projects to prefix the branch name with "wip/" so it's clear that it's a Work In Progress/Unstable branch.

**Comment by zeenix** [comment]
So what I'm saying is that let's enforce the use of 'wip/' prefix for branches on the official repo. Some projects actually have special rules for such branches, e.g non-fast-forward pushes are allowed on them.

**Pull request merged**
