### PR TITLE
qtdeclarative: add upstream patch for 49 bit addressing on ARM AArch64

### PR DESCRIPTION
**Pull request by cagriulas**
upstream patch cherry-picked from
https://codereview.qt-project.org/#/c/169892/

[GDP-549] Qt QML issue with ARM aarch64 virtual addressing

Signed-off-by: Çağrı ULAŞ <cagriulas@gmail.com>

### CODE REVIEW

**Comment by chbae** [comment]
@cagriulas 
Now rpi in GDP is using 32bit. I thought that this patch is not helpful for current rpi build. If we are using raspberrypi-64 in GDP, this patch is meaningful.

**Comment by zeenix** [comment]
@cagriulas Thanks so much for the patch. It looks really good for a first time contribution from a student.

@chbae Not sure this is for RPI, See the jira ticket: https://at.projects.genivi.org/jira/browse/GDP-549.

**Comment by chbae** [comment]
@zeenix 
This commit is only applied in meta-raspberrypi-gdp/recipes-qt/qt5/qtdeclarative_%.bbappend.

@cagriulas 
If this commit should be used in all aarch64 architecture, please move to meta-genivi-dev/recipes-qt/qt5/xxxx.

**Comment by zeenix** [comment]
@chbe ah yes, I missed that! sorry.

**Comment by cagriulas** [comment]
@chbae on JIRA description, bug happend with ARM aarch64 so I decide to make changes on RPI. But in [this commit message](https://codereview.qt-project.org/#/c/169892/), It's related with all aarch64, I think.
So what shall I do in this case?

**Comment by chbae** [comment]
@cagriulas 
In GDP, only dragonboard and m3 (NOT raspberrypi) are using aarch64. As you known, raspberrypi3 hardware supports aarch64 but current GDP is using arm 32bit.

So my suggestion is to add your patch in meta-genivi-dev/meta-genivi-dev/recipes-qt/qt5/qtdeclarative_%.bbappend with aarch64 OVERRIDE.

**Comment by zeenix** [comment]
@cagriulas As @chbae explained but there is no need for aarch64 override, the patch already has guards to ensure that this is only for 64-bit builds:

`#ifdef QV4_USE_64_BIT_VALUE_ENCODING`

i-e Just treat it as a generic Qt patch and don't need to care about which arch this is for.

**Comment by chbae** [comment]
I agree with @zeenix.

Let's apply it to all. :)

**Comment by cagriulas** [comment]
@zeenix @chbae I think, I messed up :) . Should I PR changes in fresh fork or do the changes on this PR for showing people, how it should not be done?

**Comment by zeenix** [comment]
@cagriulas that's alright, git is hard. What you do is fix your existing commits (`git rebase` is your friend, but you might want to read some tutorial on this if you haven't done rebasing before) and then do a forced push `git push -f` on your master branch.

**Review by chbae — DISMISSED** [review]
Not required merge commit. Please rebase it.

**Comment by cagriulas** [comment]
I'm totally lost. What could have been caused this. In my idea, I want combine these 3 commit:
qtdeclarative: add upstream patch for 49 bit addressing on ARM AArch64
move qtdeclarative patch to meta-genivi-dev
Merge branch 'master' into master

under this commit:
 qtdeclarative: add upstream patch for 49 bit addressing on AArch64

**Comment by chbae** [comment]
@cagriulas 

your prevous commit is not merged into master branch. So we need only ONE commit (qtdeclarative: add upstream patch for 49 bit addressing on AArch64).

**Comment by zeenix** [comment]
@cagriulas Try this in your branch:

* `git remote update`
* `git rebase origin/master -i # This is assuming your 'origin' is set to track github.com/GENIVI/meta-genivi-dev`
   * Your favourite editor will popup with your commits
   * Delete all lines with commits that are not yours
   * Put lines with commits that contain fixes to your other commits, below the relevant commits and replace 'pick' with 'squash' or 'fixup' at the beginning of the lines.
   * save and quit from editor
* The rebase should work and you can now `git push -f NAME_OF_YOUR_REMOTE`.

**Comment by gunnarx** [comment]
@cagriulas - do you want to try to fix this up or do you need some help?

I can fix it to include only the relevant commits, and force-push to the PR, but note that this means modifying your master branch (because you used master branch as the source for the PR).   GitHub allows pushing to that branch because you used it as the source for the PR.

Or I can of course just take the relevant commits, and/or create a separate PR for clarity.

I would like to merge this soon.    Please let us know how you want to proceed within a day or two.

**Comment by frznlogic** [comment]
@gunnarx I got a local copy of this fixed up already. I want to do some checks with @DunderRoffe  first however so I don't fuck something up ;).

**Comment by gunnarx** [comment]
> I got a local copy of this fixed up already

So do I actually but thanks, that's great. I'll wait.  Here is a reminder link to the [ticket](https://at.projects.genivi.org/jira/browse/GDP-549) also.

> I want to do some checks with @DunderRoffe first 

Sure. It's no problem to try a new / update the PR - the build checks should tell us if there's an issue (with compilation at least).

**Comment by slawr** [comment]
Nice to see progress on this.

Just for reference, to test on R-Car Gen 3 you would want to drop my commit [6ee0c71](https://github.com/slawr/renesas-rcar-gen3/commit/6ee0c71602c5642c98af49bf30f4d27d74626e24). It restricts the kernel from using 48-bits for VA to workaround the issue.

When you have a final patch I can test (also) if you wish.

**Comment by cagriulas** [comment]
@gunnarx
Sorry for delayed work. Nowadays, my graduation project has intensified. I pushed changes. Let me know if it's appropriate.

**Comment by DunderRoffe** [comment]
What is the status of this PR? Are there still changes to be done?

**Comment by cagriulas** [comment]
As much as I know there is nothing to be done.

**Comment by gunnarx** [comment]
@cagriulas First of all, thanks for the contribution.

I know this has been waiting a long time...  But it's a large patch to carry inside our project and I'd like to see if we can avoid it.

- Is there a way we can get meta-qt5 layer to include an appropriate Qt commit that already includes the patch and update the meta-qt5 layer to that?   According to the link you provided, it's on branch 5.6.   Well, at least the problem was found there - but I'm not sure if the fix was ultimately provided on a 5.6 branch of Qt or not?  

@DunderRoffe We could consider updating and provide a PR/patch to meta-qt5 maybe.

**Comment by gunnarx** [comment]
meta-genivi-dev is nowadays inside genivi-dev-platform repository instead and meta-genivi-dev as separate repository is deprecated. Only basic maintenance for older releases remain here.

It looks like @frznlogic worked more on this and I believe this should be done on genivi-dev-platform, so I'm closing this issue to clean up the meta-genivi-dev issue list.

**Pull request closed without merging**
