### PR TITLE
genivi-swm: Add script for resetting SOTA demo

### PR DESCRIPTION
**Pull request by leon-anavi**
Deploy bash script sota-demo-reset.sh for resetting SOTA demo by removing
GENIVI SWM SQLite database from /var/run, removing nano and its
dependencies if they have been installed.

[SWM-10] Reset SOTA Demo
[SWM-9] Move GENIVI SWM DB away from /tmp

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

### CODE REVIEW

**Review by chbae — APPROVED** [review]
I'm not sure about .sh file's location (/usr/bin).

**Comment by leon-anavi** [comment]
@chbae thank you for the feedback. Would you like to change the location of the script? Do you have an alternative directory in mind?

Best regards,
Leon

**Comment by chbae** [comment]
Now. I don't have any idea. @zeenix, @gunnarx I'm waiting for your comment.

**Comment by gunnarx** [comment]
OK by me.  This is kind of a temporary demo since full system update is coming, so I expect the script can be removed at a later time.

**Comment by gunnarx** [comment]
Good commit comment according to @zeenix standards ;), 
except that it forgot to mention the URL change from ATS to GENIVI.  I can see that the URL change cannot be in a separate commit since the new code is only in the new repo, but it could be mentioned.

For simplicity I will add this during the merge.

**Comment by gunnarx** [comment]
Merged with modified commit message as above.

@leon-anavi : Note that since the PR source branch is your master, I can push to your master.  (GitHub feature :-) If you want to avoid your master being clobbered, you can send the PRs from a dedicated feature branch.

The reason I am pushing the change is to ensure that GitHub can see that this has been merged
EDIT: Not sure what happened but maybe I hit "close" by mistake.   Anyway, it should work in theory.

**Pull request closed without merging**
