### PR TITLE
chromium rcar-gen3 integration

### PR DESCRIPTION
**Pull request by hferreiro**
Some patches to isolate rcar-gen3 specific workarounds.

### CODE REVIEW

**Comment by gunnarx** [comment]
Makes sense.  Apparently the changes had no negative effect on minnowboard (I assume they were applied?) since it builds and runs successfully already , but I guess you saw it on other platforms.  Awaiting builds.

**Comment by gunnarx** [comment]
12:53:53.610 ERROR: chromium-wayland was skipped: incompatible with machine **dragonboard-410c** (not in COMPATIBLE_MACHINE)

Currently:  **meta-genivi-dev**/... chromium-wayland_%.bbappend:
  COMPATIBLE_MACHINE_armv7ve = "(.*)"
  COMPATIBLE_MACHINE_m3ulcb = "(.*)"

and **meta-browser**/ ... ./chromium-wayland_53.0.2785.143.bb
   COMPATIBLE_MACHINE_x86 = "(.*)"
   COMPATIBLE_MACHINE_x86-64 = "(.*)"  
... and armv6 and armv7a

so that's to be expected.  (You know this of course, I was just investigating and documenting for myself and others)

Maybe supporting one at a time is the right way here.

**Comment by jaragunde** [comment]
The r-car-m3-starter-kit build probably didn't work because it's not including this commit for genivi-dev-platform: https://github.com/GENIVI/genivi-dev-platform/commit/ff7b12f8eca76e67bf22b230c465ba344e8f971e

In particular, because the modification to `conf/templates/r-car-m3-starter-kit.bblayers.conf` is missing, the compiler patch didn't get applied and that's causing a crash when building chromium.

**Comment by gunnarx** [comment]
>The r-car-m3-starter-kit build probably didn't work because it's not including this commit for genivi-dev-platform: GENIVI/genivi-dev-platform@ff7b12f
>
>In particular, because the modification to conf/templates/r-car-m3-starter-kit.bblayers.conf is missing, the compiler patch didn't get applied and that's causing a crash when building chromium.

@jaragunde Yes, I agree and also this is to be expected.  All PRs to submodules are built with the **master** branch of genivi-dev-platform when chromium is still on its feature branch.  

For all PRs this kind of mismatch between m-g-d submodule and g-d-p parent repo is a big pain we have lived with for a long time, which is why I am driving through the decision to integrate meta-genivi-dev directly into the g-d-p repo: ([email intro](http://lists.genivi.org/pipermail/genivi-projects/2017-June/thread.html)).  There could be potentially many ways to modify the CI setup to get better answers when there are many dependent parts like this, but this action is the best one for us right now.

**Comment by jaragunde** [comment]
In this situation, I think we can merge the PR into the Chromium branch.

**Pull request merged**
