### PR TITLE
Integrate Aktualizr (SOTA Client C++)

### PR DESCRIPTION
**Pull request by leon-anavi**
This GitHub pull request contains 3 patches for adding Aktualizr, the new SOTA Client written in C++, and its dependencies to the Yocto/OE recipes in GDP. The current state of Aktualizr is work in progress. I prefer to contribute it to the upstream as soon as possible. My plan is to keep updating the recipe alongside the development of Aktualizr to ensure that there are no blockers and it is always up to date.

[GDP-551] Integrate Aktualizr (SOTA Client C++)

### CODE REVIEW

**Comment by zeenix** [comment]
@leon-anavi Awesome! We should most certainly have a branch for you to keep your work into but as I've said before, I like to see PRs as a TODO for maintainers so with your permission, I'd like to close the PR for now until you think it's ready for a merge/review. What do you say?

**Comment by leon-anavi** [comment]
Hi Zeeshan,

These 3 commits are ready for a merge. Adding Aktualizr to GDP has no impact on any other components of the platform therefore it is harmless. I prefer to have several GitHub pull requests with minor changes over the time rather than one single GitHub pull request that is difficult to review. Furthermore SOTA is a hot topic during the recent GENIVI open calls and this way the development and the progress of the integration will be transparent for everyone interested. Last but not least it is a good exercise as a preparation for my talk at Embedded Linux Conference about "Contributing to Automotive Grade Linux and GENIVI Development Platform" :)

I notice a minor conflict in packagegroup-gdp-rvi. Please give a moment to rebase the last commit and resubmit it.

Best regards, Leon

**Comment by zeenix** [comment]
@leon-anavi Thanks for explaining. I'd agree with gradual approach in general and that's part of why we prefer smaller commits. However, in case of replacing some existing components with new one, IMO one PR would be better, cause:

1. I wouldn't want to maintain two different code bases at the same time in Master for the same functionality. If we're not adding the new client to our images yet, then there will be no breakages and this point is moot but then there is not much point in merging if code is not built even.
2. easier for reviewer to see the whole context.
3. it'll be more confusing for followers/readers of code with two clients in Master.

Point#2 and 3 are not very important and I can agree with you about merging already but point#1 makes me very reluctant to do so.

Good luck with your ELC talk but I don't see how merging of a WIP software will help you prepare for you talk. :)

**Comment by zeenix** [comment]
Just to clarify, I'm fine with merging this into a branch :) Of course, I mean after I get the chance to review the patches. :)

**Comment by gunnarx** [comment]
Leon Anavi makes some good points on transparency and being able to see the work in progress.  I'm favorable to a branch also.  PRs -> feature_branch -> Master, it gives more process flexibility it seems.  
Is that cool with everyone, to grow the C++ based SOTA on a branch a while and then merge/switch it over to master?

**Comment by zeenix** [comment]
@gunnarx Sure, :+1:

**Comment by leon-anavi** [comment]
Hi @zeenix, @gunnarx,

Thank you very much for the feedback. I have rebased and resolved the issues related to packagegroup-gdp-rvi. These patches include aktualizr in genivi-dev-platform and all images containing packagegroup-gdp-rvi. There are no breakages of any other components due to aktualizr or its dependencies. The name is different from the name of the SOTA client implemented in the Rust programming language so there are no blockers from this point of view too.

@zeenix, as suggested by @gunnarx, could you please review the patches and merge them in a feature branch?

Thanks,
Leon

**Comment by zeenix** [comment]
@leon-anavi Oh, I didn't mean to imply that your changes break anything. I was talking about future (time from the merge to master, till the new client is completely merged and old one dropped).

Anyway, last time I went behind github's back, the result wasn't that great. Is it not possible that we create a branch and you can then create a PR to merge to that branch?

**Comment by leon-anavi** [comment]
@zeenix yes, if you create the new branch I will be happy to submit the PR for it. Thanks in advance.

Best regards, Leon

**Comment by zeenix** [comment]
@leon-anavi sure, I just created it. Let's see if you can find it. :D

**Comment by leon-anavi** [comment]
OK, the patches have been moved to branch aktualizr. This is the new GitHub pull request: https://github.com/GENIVI/meta-genivi-dev/pull/59

Best regards, Leon

**Pull request closed without merging**
