### PR TITLE
Upgrade Qt to v5.5.1

### PR DESCRIPTION
**Pull request by chbae**
[GDP-229] Upgrade Qt to v5.5.1

### CODE REVIEW

**Comment by chbae** [comment]
This commit should be merged and tested with https://github.com/GENIVI/genivi-dev-platform/pull/19
I tested on qemux86-64 and raspberrypi3.

**Comment by tom--pollard** [comment]
I've yet to try, but apparently it is possible to directly cherry-pick the upstream ivi-shell onto qt5.5:

https://github.com/qtproject/qtwayland/commit/f144f0f71f1b75df9216c36747513444c7941c09

(taken from: http://lists.genivi.org/pipermail/genivi-projects/2016-May/002413.html)

*trying this personally, the qtwayland patch 'series' carried in meta-genivi is troublesome 

*managed to drop and rework some patches, allowing the use of the upstream commit, will test and generate PR

**Comment by chbae** [comment]
@tom--pollard That's good news. I'll check it. Thanks

I removed all qtwayland patches and only applied qtwayland upstream ivishell.
However, the HMI app process is running but I see only black screen. I'll investigate more.

**Comment by chbae** [comment]
I remove unnecessary patches and I'll make only 2 patches but I'm not sure about 5.7 cherry-picking.

**Comment by chbae** [comment]
@tom--pollard 

I removed unnecesasry patch but I'm applied upstream ivishell.

This is my final suggestion and it's good to integrate upstrame patch after this change or 5.7 upgrade.

**Comment by tom--pollard** [comment]
@chbae This is more or less what I ended up with, although I didn't remove quite as many of the patches as quite frankly I could not find any information to whether they were still important or not. I also like that you reimplemented the qwaylandwindow minimize patch to inline with the upstream patch. 

I was talking to @rzr about this as the rest of the changes from  https://github.com/GENIVI/meta-genivi-dev/blob/master/meta-genivi-dev/recipes-qt/qt5/qtwayland/0017-xdg-shell-Add-minimize-feature-to-QWindow-using-wayl.patch for xdg minimize patch were up-streamed into qtwayland 5.5.1 except the qwaylandwindow changes, but they should be from 5.6? I think

What ref/source was this upstream patch taken out of interest, as it doesn't seem to be the one I linked from 5.7? The only change I had to make for it to compile was a .gitignore diff, which is irrelevant here.

**Comment by rzr** [comment]
Note that if you're using a weston wayland-1.9 or later I am not sure you have xdg-shell supported as I did not maintain that feature after latest Tizen:IVI release.

Here is history of supported versions : 

http://code.qt.io/cgit/qt/qtwayland.git/log/?qt=author&q=coval

**Comment by mirrorswp** [comment]
@tom--pollard 

Yes, only .gitignore conflict but I don't know how to apply it. I need time to investigate it.
Also we need qwaylandwindow patch :)

So I thought that it's very similar with current patches.

As @rzr said, we don't need xdg shell anymore. We only use ivi-shell right?

This patches work fine on rpi2 and two problem may be solved (rpi keyboard problem and double-clicking problem)

**Comment by rzr** [comment]
Yea xdg-shell was a requirement for desktop use case.

In longer term it would be good that ivi-shell support WL shell and xdg-shell if possible.

**Comment by tom--pollard** [comment]
My rework of the ivi shell qywaylandwindow minimize patch for the 5.7 ivi shell shell support is here:

http://paste.baserock.org/egodocasiz

**Comment by chbae** [comment]
> http://paste.baserock.org/egodocasiz

This is same with https://github.com/chbae/meta-genivi-dev/blob/feature/gdp10qt5.5/meta-genivi-dev/recipes-qt/qt5/qtwayland/0002-qwaylandwindow-add-support-for-IVI-Surface-ID-proper.patch.
You may get the build error about "find not to qwaylandivisurface_p.h"

@tom--pollard  Did you build successfully?

**Comment by tom--pollard** [comment]
Hi @chbae I've built the current revision of the PR for porter and reported my findings in the related jira ticket GDP-229. All in all I think this PR and its revision has helped to consolidate the qtwayland patch series, which will help with management going forward to later qt versions. +1

**Comment by chbae** [comment]
@tom--pollard 
Thanks. I'll merge this tonight :)

**Pull request merged**
