### PR TITLE
meta-iot-web: Ship iotivity-node using metapackage

### PR DESCRIPTION
**Pull request by rzr**
Please first merge:
https://github.com/GENIVI/genivi-dev-platform/pull/61

Metapackage packagegroup-nodejs-runtime pulls
IoTivity NodeJS bindings and dependencies.

[GDP-160] meta-genivi-ocf-demo merging

Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by gunnarx** [comment]
So packagegroup-nodejs-runtime is missing because layer meta-iot-web is needed from the other PR which needs merge first as @rzr said.  --> all checks fail, this happens when we have the inter-dependencies.  No single PR check can confirm.

If you want CI to confirm that it won't break stuff -the way is to first merge this m-g-d, then look at the CI pipeline that always builds g-d-p with the tip of m-g-d.   That resolves the inter-dependency so that you can confirm g-d-p is alright before bumping the submodule in g-d-p master branch.

**Comment by zeenix** [comment]
I merged the related g-d-p PR so now go.cd builds should succeed.

**Comment by zeenix** [comment]
CI fails now again due to agent issues. :( I'll check with @gunnarx..

**Comment by gunnarx** [comment]
> CI fails now again due to agent issues. :( I'll check with @gunnarx..

No the GitHub check report links are still pointing to the old builds. 
These should rebuild soon once there is capacity for it.

(Remember they always point to specific build instances. The font is small but we can see they were built 17 February, i.e. when the PR was first introduced)

**Comment by gunnarx** [comment]
You merged in the opposite order I suggested, but I would have expected that to work too.   I'm was not sure why these checks do not rebuild, but looking at the logs, this pr is now behind master by one commit:

$ git log master --not pr_63

yields:

commit 4c7a465e279478d8119d5d200a755d5311f76731 (master)
Author: Changhyeok Bae <changhyeok.bae@gmail.com>
    Drop Faytech support

and so it needs rebasing.  If it's rebased it *should* be rebuilt by CI.  Thinking of this theoretically, that seems the only way we can be 100% sure a PR is OK in combination with that missing commit, so maybe the system is smarter than us (me) here...   Suffice to say, the current CI setup we have is not smart enough to rebase PRs automatically, although I could imagine scripting such instructions into a pipeline in theory.

@rzr are you online to do a quick rebase of this PR on m-g-d master? 
(Actually @zeenix has the capability to do it also I learned today.)

**Comment by gunnarx** [comment]
We're now using this PR to kind of understand the CI setup deeper.  But looking at the content itself it certainly looks completely fail safe.   But you decide @zeenix +1 for merging from me.

**Comment by rzr** [comment]
Ok I can rebase this

**Comment by zeenix** [comment]
@gunnarx Sorry I missed your suggestion but I'm sure I merged in the correct order: First merge the required (nonbreaking) change in g-d-p to add the layer and then merge the actual change in m-g-d. i-e not breaking the build on any of the commits.

@rzr Cool, thanks. Once you have pushed  rebase, hopefully CI will be all green and we can merge.

**Review by zeenix — CHANGES_REQUESTED** [review]
While you're rebase, could you also please fix early line break in description at the same time? If you recall we had a discussion about this.

**Comment by gunnarx** [comment]
Yes you did merge in the right order from that perspective.

This is not completely obvious for sure...   One thing I would point out though - since m-g-d layer doesn't create much on its own without the genivi-dev-platform framework to build it in, merging this into meta-genivi-dev is a breaking change that we have the luxury to ignore.  We need to bump the submodule before GDP build starts using it and before that it doesn't break any real build that we have (or anyone else in the universe I bet*).  So because of submodules locking to a particular version, merging into m-g-d before g-d-p makes sense a lot of times for these co-dependent situations.

*Only the CI pipeline we have for that specific purpose may fail - the one building using the tip of meta-genivi-dev all the time, no matter what the submodule points to.

**Comment by zeenix** [comment]
@gunnarx I don't agree. Git master should always be buildable. If our CI tools can't handle the correct order of merging, then they need to be fixed somehow but we should not ever break the build at any given time on purpose.

**Comment by zeenix** [comment]
@rzr Still breaking too early but in this case the it's going to be 2 lines anyway so I'm merging.. :)

**Review by zeenix — APPROVED** [review]

**Comment by rzr** [comment]
Ok thx, I will double check to make sure everything is fine, and then update:
https://wiki.iotivity.org/automotive

**Comment by chbae** [comment]
iotivity-node and iotivity-rest-api-server doesn't support aarch64 and it is the cause of breaking dragonboard-410c build. Now I'll create PR to support aarch64 in meta-iot-web layer.

@rzr How can I test?

**Comment by rzr** [comment]
Hi @chbae there a few notes at 
https://wiki.iotivity.org/automotive#work_in_progress

I don't have any aarch64 but I can test your patch along my demo codes (I will have to update documentation on that wiki too).

Ping me online if you need more support.

**Pull request merged**
