### PR TITLE
Add htop to gdp-dev packagegroup

### PR DESCRIPTION
**Pull request by tom--pollard**
[GDP-436] Add htop to GDP Image

### CODE REVIEW

**Comment by RobertAJMarshall** [comment]
Builds ok for me on qemu. Nice to have - though might you want to leave it out so that it's available as an adding example in a future hands on?

**Comment by chbae** [comment]
Looks good. but i'll test today on raspberrypi3.

**Comment by tom--pollard** [comment]
@RobertAJMarshall I think 6 months is too far away to consider that, I'm sure another example could be produced for then etc :)

**Comment by tom--pollard** [comment]
This still needs +- 1

**Comment by chbae** [comment]
Sorry. I didn't test yet. I'll test soon. :)

**Comment by locust2001** [comment]
I works fine on rpi3.

**Comment by chbae** [comment]
It works fine on rpi3.

**Pull request merged**
