### PR TITLE
TEST PR, do not merge

### PR DESCRIPTION
**Pull request by palvarez89**

### CODE REVIEW

**Comment by gunnarx** [comment]
Testing close and open PR if that has any effect on Go PR build now.  Don't think it will but who knows.

**Comment by gunnarx** [comment]
opening again

**Comment by gunnarx** [comment]
Hmm, palvarez89, did you notice the topmost commit on this one is a merge commit?
[#71](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/issues/71) in the plugin as we discussed yesterday...

**Comment by palvarez89** [comment]
hmm.. maybe that's what's happening here. I'll resubmit the PR

**Comment by palvarez89** [comment]
Closed as everything seems to work now.

**Pull request closed without merging**
