### PR TITLE
qtimageformats: Add libwebp for dragonboard

### PR DESCRIPTION
**Pull request by chbae**
[GDP-438] GDP SDK build fails for Dragonboard

Signed-off-by: Changhyeok Bae changhyeok.bae@gmail.com

### CODE REVIEW

**Comment by tom--pollard** [comment]
This builds for me, can't confirm dragonboard compatibility though. +1

**Comment by chbae** [comment]
@gunnarx 
please review this.

**Comment by gunnarx** [comment]
Yes, I built the SDK separately with success. All the PR builds [(example)](https://go.genivi.org/go/tab/build/detail/GDP-Yocto-QEMU_x86-64-meta-genivi-dev-GITHUB-PR/36/build/1/init_and_bitbake) have also been done successfully it seems.  It does not look like the PR build result was reported to GitHub however? - let's monitor that...

+1 I recommend merging.  As soon as that is done, I'll build the Dragonboard version of the SDE.

**Comment by gunnarx** [comment]
Great work @chbae - thanks for your help

**Pull request merged**
