### PR TITLE
rpi-config: Fix bluetooth launch issue in rpi3

### PR DESCRIPTION
**Pull request by chbae**
[GDP-333] Bluetooth not working on RPI3 (brcm4348.service failed)

Signed-off-by: Changhyeok Bae changhyeok.bae@gmail.com

### CODE REVIEW

**Comment by chbae** [comment]
@tom--pollard, @RobertAJMarshall

Please review this. With this, I tested on rpi3 and I'll change init.sh (for rpi3 support) in genivi-dev-platform after merging this.

**Comment by RobertAJMarshall** [comment]
Looks good to me (though unable to test that it does what it says)

**Comment by nicolas4119** [comment]
It seems working, i can now use hcitool lescan for example on my rpi3. 
The only problem left is that i need to manually : 
 rfkill unblock bluetooth
hciconfig hci0 up
Then bt controller works well .

**Comment by tom--pollard** [comment]
Thanks all, merged

**Pull request merged**
