### PR TITLE
[GDP-277] reference Master page in README

### PR DESCRIPTION
**Pull request by RobertAJMarshall**
Also remove much of the changes suggested which are now covered in ${machine}.local.conf

### CODE REVIEW

**Comment by chbae** [comment]
@RobertAJMarshall 
1. Why don't you move jira issue number from title to message?
2. I prefer to using title "README: change ....." but it's not mandatory. up to you.

Thanks.

**Comment by RobertAJMarshall** [comment]
I thought Tom preferred the JIRA id in the title or did I misunderstand him?

**Comment by chbae** [comment]
> I thought Tom preferred the JIRA id in the title or did I misunderstand him?

Let's talk about this in our meeting tonight.
Yocto is using below format for commit message.
- title: component name: change summary
- messages: detail description included in issue number.

**Comment by tom--pollard** [comment]
@RobertAJMarshall I prefer jira tickets in the message :)

**Comment by RobertAJMarshall** [comment]
Clearly I was confused! Commit message fixed

**Pull request merged**
