### PR TITLE
readme: add Renesas R-Car (Gen 3) M3 Starter Kit board

### PR DESCRIPTION
**Pull request by slawr**
As requested by @gunnarx I have gone ahead and created this PR to add the recently merged Renesas R-Car (Gen 3) M3 Starter Kit board to the readme.

### CODE REVIEW

**Review by chbae — APPROVED** [review]

**Comment by zeenix** [comment]
@slawr Thanks. Before we merge this, I'd want a concern of mine about hashes in README resolved first: https://github.com/GENIVI/meta-genivi-dev/pull/76#pullrequestreview-29144190

**Comment by slawr** [comment]
@zeenix I agree that SHA lists could be somewhat painful to maintain as a readme update would follow every submodule update. Although of course here I'm just following an existing convention.

It's just a guess but I suspect it goes back to a time before submodules were used. It was likely following the convention in meta-ivi of listing the SHAs that are known to work.

It seems to me that your comment relates more to a separate change request, i.e. it should be a separate change. Perhaps after this.

**Comment by gunnarx** [comment]
> @zeenix I agree that SHA lists could be somewhat painful to maintain as a readme update would follow every submodule update. Although of course here I'm just following an existing convention.

Not quite that bad because we don't maintain it for the GDP project repository (with submodules) since it would be both painful and redundant. But whenever dependencies to meta-genivi-dev change then the README needs to change.  So there's a logic behind this.  But I still don't like it.  Moving the rest of the discussion to #76 where it belongs.

**Comment by slawr** [comment]
> Not quite that bad because we don't maintain it for the GDP project repository (with submodules) since it would be both painful and redundant. But whenever dependencies to meta-genivi-dev change then the README needs to change. So there's a logic behind this. But I still don't like it. Moving the rest of the discussion to #76 where it belongs.

Yes your right. I was mixing up projects when commenting. Note to self don't try to comment quickly when your on holiday :)

**Comment by zeenix** [comment]
since @chbae didn't act in time, I'll merge this and let him worry about #76 :)

**Pull request merged**
