### PR TITLE
aktualizr: Update version

### PR DESCRIPTION
**Pull request by leon-anavi**
Update Aktualizr to the latest version that uses the upstream version of
rvi_lib and the log API.

[GDP-551] Integrate Aktualizr (SOTA Client C++)

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

### CODE REVIEW

**Review by chbae — APPROVED** [review]

**Review by zeenix — CHANGES_REQUESTED** [review]
Looks good. @chbae and I agreed that on update commits like these we should specify the version/commithash in the shortlog.

**Comment by leon-anavi** [comment]
OK, I have updated the git commit log and added the commithash.

**Review by zeenix — APPROVED** [review]
I meant the shortlog but since @chbae didn't object I don't think it's a big deal. :)

**Comment by leon-anavi** [comment]
Thank you for merging it. I have created a GitHub pull request for updating meta-genivi-dev in genivi-dev-platform: https://github.com/GENIVI/genivi-dev-platform/pull/80

Best regards,
Leon

**Pull request merged**
