### PR TITLE
Drop Faytech support

### PR DESCRIPTION
**Pull request by chbae**
Dropping Faytech monitor support since they've been known to cause
various problems and therefore make maintenance hard. List of currently
supported peripherals can be found at:
https://at.projects.genivi.org/wiki/display/GDP/GDP+and+peripherals

[GDP-546] Drop Faytech support

Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>

### CODE REVIEW

**Review by zeenix — CHANGES_REQUESTED** [review]
Awesome! Same comment as g-d-p patch though. You can use the same text I provided in that review.

**Comment by tom--pollard** [comment]
Is there any point dropping support before the new kernels from the Morty upgrade are merged?

**Comment by zeenix** [comment]
@tom--pollard what's the connection?

**Comment by tom--pollard** [comment]
@zeenix I'd got the impression that you didn't want to maintain kernel driver patches for the faytech when new kernels were introduced into GDP leading to rebasing. To me it would make sense to drop the support at the time Morty is merged for GDP12 (Genivi has spent over a year recommending people buy this monitor)

**Comment by zeenix** [comment]
@tom--pollard no, i just don't want to maintain the support anymore in general. :) I closed the bugs related to faytech already and updated wikipages already so this is just the last step.

**Review by zeenix — APPROVED** [review]

**Pull request merged**
