### PR TITLE
README.md: Update readme file to lastest version

### PR DESCRIPTION
**Pull request by chbae**
Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>

### CODE REVIEW

**Review by zeenix — CHANGES_REQUESTED** [review]
Oh I didn't realize README had commit hashes. Two things:

* Is it a good idea to keep these hashes in README? They'll most often be outdated since we update submodules very often and that just beats the point of documenting them here. So I'll suggest we instead just remove them. Perhaps we can instead specify the tracked branch?

* The commit log confused me at first. It sounds like the version of README is being updated. I'd instead go for: "Update submodule hashes" (prefix already specifies the file being changed).

**Comment by gunnarx** [comment]
This has two reasons I think:

1. meta-ivi does the same - document hashes in the README, and I guess any /reusable/ layer must document its dependencies.

2. It has been discussed before and remains based on the idea that meta-genivi-dev might live a life independent of genivi-dev-platform, i.e. be adopted by other projects.  But in practice I don't think it is.  Instead I think the strategy must be to share technology with other projects through all **other layers** (like meta-ivi) in GDP, and that meta-genivi-dev has (should only have, in my opinion) those few things that are unique for GDP only.  

As long as it is an independent repo I guess the hashes need to be there for good measure, but merging m-g-d it into the g-d-p repo would get rid of also the need to update this README.

**If** we agree meta-genivi-dev is only used in GDP then this is just another activity that is more  ritual and ceremony than actually useful.  In my opinion we don't have time for such activities.

**Comment by gunnarx** [comment]
> Perhaps we can instead specify the tracked branch?

Sounds like an acceptable compromise for the short term.

**Comment by slawr** [comment]
> meta-ivi does the same - document hashes in the README, and I guess any /reusable/ layer must document its dependencies.

I think that is a very valid point. It can be frustrating to get build errors for a dev not closely working on the project. That can happen somewhat easily when for instance a Genivi layer carries some fix whilst upstream catches up. So I do see value in documenting what is known to work. Whether you do it here or in the wiki I guess is up for discussion. Readme has the benefit of always being correct (if maintained) whilst the wiki might only be updated on major releases.

On your wider point about m-g-d being independent it is difficult I think. I think you were right in trying to make meta-ivi and m-g-d non-partisan so others might join its development. In the same way meta-ivi shows how to knit genivi components into the Poky ref distro to make an IVI m/w, m-g-d shows how to knit higher level components such as App frameworks and Qt. So it could be argued it could be adopted and contributed to by others. In practise as you say that is not happening widely yet, or more accurately we have no evidence of that, so it may be mute.

**Pull request closed without merging**
