### PR TITLE
Upgrade GDP Master to baseline 11 (MIRANDA)

### PR DESCRIPTION
**Pull request by chbae**
[GDP-281] Upgrade GDP Master to baseline 11 (MIRANDA)

### CODE REVIEW

**Comment by tom--pollard** [comment]
Thanks for accepting my changes to your feature branch for this PR @chbae 

+1 tested on qemux86-64, with weston 1.11 + ivi-extension 1.10.90 enforced in local.inc

**Comment by chbae** [comment]
@RobertAJMarshall  Please your review

@tom--pollard  Thanks so much for helping this work. :)

I'll test tomorrow on my rpi3.

**Comment by chbae** [comment]
This PR should be merged with https://github.com/GENIVI/genivi-dev-platform/pull/27

**Comment by RobertAJMarshall** [comment]
I'm just testing a build with your branch

**Comment by RobertAJMarshall** [comment]
+1 - builds and runs ok here too!

**Comment by chbae** [comment]
+1 It works fine on rpi3 and dragonboard-410c.

**Pull request merged**
