### PR TITLE
Chromium multi seat

### PR DESCRIPTION
**Pull request by jaragunde**
Multi-seat implementation for Chromium (GDP-604) and the patches required to fix GDP-616 and GDP-615.

### CODE REVIEW

**Review by gunnarx — CHANGES_REQUESTED** [review]
This refers to: 9ca2f6ff9

I think we should prefer not to carry patches like this in the layer recipes.  They tend to just get old and rotten.  We're on a quest to improve quality and remove these types of hacks so I'd rather avoid adding more.  

I know this bug was fixed on a later version.  But why not propose to  backport this and keep a maintenance branch for wayland-ivi-extension instead.

**Review by gunnarx — CHANGES_REQUESTED** [review]
This refers to:  	5f77592

@jaragunde - What's the status of acceptance of this in ozone upstream?

It's a huge patch...  Let's prefer git repos instead of putting it in the layer.  Either we get this accepted in ozone or we should fork ozone and keep the code in a git branch, IMHO.

**Comment by gunnarx** [comment]
OK for 1f335a4

**Comment by gunnarx** [comment]
Update from today's sync-up call:  We decided @jaragunde will point the build to his fork of ozone instead of keeping a large patch around.  For wayland-ivi-extension bugfix I will propose it to the LM team.

**Comment by gunnarx** [comment]
@jaragunde Since we're doing quite major rework on this, let's also close this one and resubmit later.
The [meta-genivi-dev merge into g-d-p](http://lists.genivi.org/pipermail/genivi-projects/2017-June/005539.html) is happening now so I'm trying to remove as many m-g-d PRs as possible.   This PR will be for g-d-p next time.

**Comment by jaragunde** [comment]
Alright, closing this PR. The `chromium-multi-seat` patch will still contain the WIP patches for the integration of the feature.

**Pull request closed without merging**
