### PR TITLE
Add tools-debug to genivi-dev-platform image by default, as now 'development platform'

### PR DESCRIPTION
**Pull request by tom--pollard**
…lopment platform'

### CODE REVIEW

**Comment by tom--pollard** [comment]
I'm also open to having any extra packagegroups that will aid development/debugging

**Comment by chbae** [comment]
One of my idea is that why don't we create development image instead of genivi-dev-platform build.
And then we'll add tools-debug and tools-profile .... for debug.
ex) bitbake genivi-dev-platform-devel

**Comment by chbae** [comment]
About title, I recommend that it's shorter than 52 char then it's readable.

FYI https://github.com/erlang/otp/wiki/writing-good-commit-messages

**Comment by tom--pollard** [comment]
Fair point about the commit title, I mangled the new line by accident. Genivi-dev-platform-devel I'm really against (not just that the word development occurs twice), if we're pushing to be a development platform then tools associated with such a term should be default, in my opinion.

**Comment by tom--pollard** [comment]
Do you have any opinion on this @jonathanmaw ?

**Comment by jonathanmaw** [comment]
@tom--pollard I am in favour of adding more debugging features, and am currently testing out what tools are added by this change.

**Comment by jonathanmaw** [comment]
It adds gdb, gdbserver and strace. These are useful tools I'd expect to see in a development platform, so I fully support this merge.

**Comment by chbae** [comment]
I agree about new image. Now It's time to think about commit message rule.

Thanks for your opinion.

**Pull request merged**
