### PR TITLE
Add packagegroup-gdp-rvi to genivi-dev-platform image

### PR DESCRIPTION
**Pull request by tom--pollard**
Group rvi components into a 'rvi' packagegroup, and include this in the default GDP image. This approach will allow new components from rvi to be added once to this packagegroup. Including @leon-anavi as he brought rvi sota/core into GDP

### CODE REVIEW

**Comment by tom--pollard** [comment]
@chbae do you have any preference here?

**Comment by chbae** [comment]
@tom--pollard 
1. Commit message
   Why don't you change to commit message?
   I recommend that issue number is added in detail notes (not title)
2. Readme file
   We need to update https://github.com/GENIVI/meta-genivi-dev/blob/master/README.md
3. layer.conf for layer dependency 
   We also need to update https://github.com/GENIVI/meta-genivi-dev/blob/master/meta-genivi-dev/conf/layer.conf

Those don't affect in runtime but good to change.

## My recommendation for commit message

Add packagegroup-gdp-rvi to genivi-dev-platform image

[GDP-159] meta-rvi yocto layer merging

**Comment by tom--pollard** [comment]
@chbae I'm not sure what your point is with 3. ? And sure about the jira ticket inclusion, it could go in the body of the commit, however this is not really an issue

**Comment by chbae** [comment]
@tom--pollard 

You are right. number 3 is just my recommendation because we didn't decide commit message rule. It's up to you. :)

**Comment by tom--pollard** [comment]
Thanks for the feedback as always @chbae :)

**Pull request merged**
