### PR TITLE
Upgrade qt to v5.6.0

### PR DESCRIPTION
**Pull request by chbae**
[GDP-280] Upgrade Qt to v5.6

### CODE REVIEW

**Comment by chbae** [comment]
This PR should be merged with https://github.com/GENIVI/genivi-dev-platform/pull/25

**Comment by chbae** [comment]
@tom--pollard, @RobertAJMarshall
I tested on my raspberrypi3. Please review this PR.

Thanks

**Comment by RobertAJMarshall** [comment]
The qemux86-64 image builds for me

**Comment by chbae** [comment]
@tom--pollard, @RobertAJMarshall 
Please +1 or -1 after your testing. I'll merge this change.

Thanks.

**Comment by tom--pollard** [comment]
+1, but it may be quicker just to merge the ivi11/yocto2.1 upgrade in a single PR, including this support for krogon qt5.6.1

**Comment by chbae** [comment]
I would like to separate qt and ivi upgrade. So I'll merge.

Thanks @RobertAJMarshall and @tom--pollard

**Pull request merged**
